pages:
  - Home:
    - Introduction: index.md
  - Software:
    - Overview: software/index.md
    - Release Notes: software/releasenotes.md
    - Testing Guidelines: software/testingguidelines.md
    - Contributing: contributing.md
    - Getting Help: help.md
  - Overview:
    - Data Protection: data_protection.md
    - Contributors: contributors.md
    - References: references.md
    - License: license.md
  - mCerebrum:
    - Overview: mCerebrum/index.md
    - Getting Started: mCerebrum/gettingStarted.md
    - Configurations: mCerebrum/configurations.md
    - Configuration-mCerebrum: mCerebrum/configuration-mCerebrum.md
    - Configuration-DataKit: mCerebrum/configuration-datakit.md
    - Configuration-Sensors: mCerebrum/configuration-sensors.md
    - Configuration-Plotter: mCerebrum/configuration-plotter.md
    - Configuration-EMA: mCerebrum/configuration-ema.md
    - Configuration-EMA Scheduler: mCerebrum/configuration-emascheduler.md
    - Troubleshooting: mCerebrum/troubleshooting.md
  - Cerebral Cortex:
    - Overview: cerebralcortex/index.md
    - API: cerebralcortex/api.md
  - Feedback: feedback.md

extra:
  palette:
    primary: 'blue'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: github
      link: https://github.com/MD2Korg
    - type: twitter
      link: https://twitter.com/MD2Korg


site_name: MD2K Software and Training
site_description: mCerbrum and Cerebral Cortex software documentation and training material
site_author: MD2K.org
site_url: http://docs.md2k.org/

copyright: 'Copyright &copy; 2017 MD2K Center of Excellence'
google_analytics: ['UA-77812263-1', 'auto']

repo_url: https://github.com/MD2Korg/
edit_uri: md2korg.github.io/edit/dev/docs/

remote_branch: master

extra_css: [css/md2k.css]

theme_dir: 'mkdocs-material/material'


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.githubemoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
